/** DataOps Close V1 staging authority. Not enabled until immutable deployment identity is released. */
const DATAOPS_CLOSE_V1='DATAOPS_CLOSE_V1';
const DATAOPS_CLOSE_PROPERTIES=Object.freeze({DEPLOYMENT_ID:'ONEAPP_DATAOPS_CLOSE_DEPLOYMENT_ID',DEPLOYMENT_VERSION:'ONEAPP_DATAOPS_CLOSE_DEPLOYMENT_VERSION',GIT_COMMIT:'ONEAPP_DATAOPS_CLOSE_GIT_COMMIT',POINTERS:'ONEAPP_DATAOPS_CLOSE_POINTERS_JSON'});
const DATAOPS_CLOSE_SHEETS=Object.freeze({SEALS:'DataOpsClose_Seals',LEASES:'DataOpsClose_Leases',CHUNKS:'DataOpsClose_Chunks',INDEX:'DataOpsClose_Index',BASELINES:'DataOpsClose_Baselines',AUDIT:'DataOpsClose_Audit'});
const DATAOPS_CLOSE_ACTIONS=Object.freeze(['dataops_close_ping','dataops_close_context','dataops_close_seal','dataops_close_prepare','dataops_close_write_chunks','dataops_close_commit','dataops_close_abort']);
const DATAOPS_V1_SECURITY=Object.freeze({MODE_PROPERTY:'ONEAPP_DATAOPS_V1_SECURITY_MODE',LEGACY:'LEGACY_COMPATIBLE',CUTOVER:'SERVER_FIRST_V1',CAPABILITY:'DATAOPS_SNAPSHOT_V1_SECURITY_V1',READ_ROLE:'DATAOPS_SNAPSHOT_V1_READ',WRITE_ROLE:'DATAOPS_SNAPSHOT_V1_WRITE'});
function dataOpsCloseText(value){return String(value===undefined||value===null?'':value).trim();}
function dataOpsV1SecurityMode(properties){return dataOpsCloseText(properties.getProperty(DATAOPS_V1_SECURITY.MODE_PROPERTY))===DATAOPS_V1_SECURITY.CUTOVER?DATAOPS_V1_SECURITY.CUTOVER:DATAOPS_V1_SECURITY.LEGACY;}
function dataOpsV1SecurityCapability(properties){const mode=dataOpsV1SecurityMode(properties);return{capabilityVersion:DATAOPS_V1_SECURITY.CAPABILITY,mode,deploymentId:dataOpsCloseText(properties.getProperty(DATAOPS_CLOSE_PROPERTIES.DEPLOYMENT_ID)),deploymentVersion:dataOpsCloseText(properties.getProperty(DATAOPS_CLOSE_PROPERTIES.DEPLOYMENT_VERSION)),gitCommit:dataOpsCloseText(properties.getProperty(DATAOPS_CLOSE_PROPERTIES.GIT_COMMIT)),readAuthRequired:mode===DATAOPS_V1_SECURITY.CUTOVER,writeAuthRequired:mode===DATAOPS_V1_SECURITY.CUTOVER,roles:[DATAOPS_V1_SECURITY.READ_ROLE,DATAOPS_V1_SECURITY.WRITE_ROLE],actions:['dataops_snapshot_get','dataops_snapshot_commit']};}
function dataOpsV1RequireAccess(payload,operation,properties){if(dataOpsV1SecurityMode(properties)!==DATAOPS_V1_SECURITY.CUTOVER)return{legacyCompatible:true};const role=operation==='WRITE'?DATAOPS_V1_SECURITY.WRITE_ROLE:DATAOPS_V1_SECURITY.READ_ROLE;return dataOpsSituationRequireAuth(payload,role,properties);}
function dataOpsV1PreflightAction(action,payload,properties){if(action==='dataops_snapshot_commit')return dataOpsV1RequireAccess(payload,'WRITE',properties);if(action==='dataops_snapshot_get')return dataOpsV1RequireAccess(payload,'READ',properties);return null;}
function dataOpsCloseDeployment(properties){const result={deploymentId:dataOpsCloseText(properties.getProperty(DATAOPS_CLOSE_PROPERTIES.DEPLOYMENT_ID)),deploymentVersion:dataOpsCloseText(properties.getProperty(DATAOPS_CLOSE_PROPERTIES.DEPLOYMENT_VERSION)),gitCommit:dataOpsCloseText(properties.getProperty(DATAOPS_CLOSE_PROPERTIES.GIT_COMMIT))};if(!result.deploymentId||!result.deploymentVersion||!result.gitCommit)throw new Error('DATAOPS_CLOSE_DEPLOYMENT_NOT_RELEASED');return result;}
function dataOpsCloseSheet(ss,name,headers){let sheet=ss.getSheetByName(name);if(!sheet)sheet=ss.insertSheet(name);if(sheet.getLastRow()===0)sheet.appendRow(headers);return sheet;}
function dataOpsCloseRows(sheet){if(sheet.getLastRow()<2)return[];const values=sheet.getRange(2,1,sheet.getLastRow()-1,sheet.getLastColumn()).getValues(),headers=sheet.getRange(1,1,1,sheet.getLastColumn()).getValues()[0];return values.map((row,index)=>headers.reduce((out,key,column)=>{out[key]=row[column];return out;},{_row:index+2}));}
function dataOpsCloseAudit(ss,row){dataOpsCloseSheet(ss,DATAOPS_CLOSE_SHEETS.AUDIT,['auditId','action','actorId','roleIds','scopeDigest','seriesId','commandId','result','detail','createdAt']).appendRow([Utilities.getUuid(),row.action,row.actorId,(row.roleIds||[]).join(','),row.scopeDigest,row.seriesId||'',row.commandId||'',row.result||'SUCCESS',JSON.stringify(row.detail||{}),new Date().toISOString()]);}
function dataOpsCloseLeaseSheet(ss){return dataOpsCloseSheet(ss,DATAOPS_CLOSE_SHEETS.LEASES,['seriesId','commandId','idempotencyKey','fingerprint','status','stageId','expiresAt','updatedAt','sealedVerification','actionType','expectedSeriesHeadRevision','targetRevision','actorId','scopeDigest','sourceSealId','sourceSealReceiptFingerprint','stageManifest']);}
function dataOpsCloseChunkSheet(ss){return dataOpsCloseSheet(ss,DATAOPS_CLOSE_SHEETS.CHUNKS,['stageId','kind','chunkIndex','chunkDigest','content','status','updatedAt']);}
function dataOpsCloseIndexSheet(ss){return dataOpsCloseSheet(ss,DATAOPS_CLOSE_SHEETS.INDEX,['closeRevisionId','seriesId','revision','actionType','sourceADigest','resultBDigest','issueDecisionDigest','finalReceiptFingerprint','receipt','createdAt','stageId','companyId','closeBusinessDate','reportDigest','commandId']);}
function dataOpsCloseSealSheet(ss){return dataOpsCloseSheet(ss,DATAOPS_CLOSE_SHEETS.SEALS,['sourceSealId','closeSeriesId','sourceADigest','closeReadTokenDigest','orderqHeadDigestAtSeal','dataopsHeadDigestAtSeal','orderqDeployment','dataopsDeployment','capabilityDigest','sealedBy','sealedAt','receiptFingerprint','receipt']);}
function dataOpsCloseBaselineSheet(ss){return dataOpsCloseSheet(ss,DATAOPS_CLOSE_SHEETS.BASELINES,['baselineId','seriesId','companyId','closeBusinessDate','currency','contextDigest','payload','approvedBy','approvalReason','approvedAt','status']);}
function dataOpsCloseFindLease(ss,seriesId){return dataOpsCloseRows(dataOpsCloseLeaseSheet(ss)).find(row=>dataOpsCloseText(row.seriesId)===seriesId);}
function dataOpsCloseFindSeal(ss,sourceSealId){const row=dataOpsCloseRows(dataOpsCloseSealSheet(ss)).find(item=>dataOpsCloseText(item.sourceSealId)===dataOpsCloseText(sourceSealId));if(!row)throw new Error('CLOSE_SOURCE_SEAL_NOT_FOUND');const receipt=JSON.parse(row.receipt||'{}'),unsigned={...receipt};delete unsigned.receiptFingerprint;if(receipt.receiptFingerprint!==row.receiptFingerprint||dataOpsSituationDigest(unsigned)!==receipt.receiptFingerprint)throw new Error('CLOSE_SOURCE_SEAL_INVALID');return{row,receipt};}
function dataOpsCloseStagePayload(ss,stageId,kind){const rows=dataOpsCloseRows(dataOpsCloseChunkSheet(ss)).filter(row=>row.stageId===stageId&&row.kind===kind).sort((a,b)=>Number(a.chunkIndex)-Number(b.chunkIndex));return{rows,content:rows.map(row=>String(row.content||'')).join('')};}
function dataOpsCloseReadStageJson(ss,stageId,kind){const staged=dataOpsCloseStagePayload(ss,stageId,kind);if(!staged.rows.length||staged.rows.some((row,index)=>row.status!=='VERIFIED'||Number(row.chunkIndex)!==index))throw new Error('CLOSE_STAGE_READBACK_REQUIRED');try{return JSON.parse(staged.content);}catch(_error){throw new Error('CLOSE_STAGE_READBACK_INVALID');}}
function dataOpsClosePointers(properties){try{return JSON.parse(properties.getProperty(DATAOPS_CLOSE_PROPERTIES.POINTERS)||'{}');}catch(_error){throw new Error('CLOSE_POINTER_INVALID');}}
function dataOpsCloseContext(ss,payload,auth,properties){
  const seriesId=dataOpsCloseText(payload.closeSeriesId),companyId=dataOpsCloseText(payload.companyId),closeBusinessDate=dataOpsCloseText(payload.closeBusinessDate);if(!seriesId||!companyId||!/^\d{4}-\d{2}-\d{2}$/.test(closeBusinessDate))throw new Error('CLOSE_CONTEXT_REQUIRED');
  const pointer=dataOpsClosePointers(properties)[seriesId]||null,indexes=dataOpsCloseRows(dataOpsCloseIndexSheet(ss)).filter(row=>dataOpsCloseText(row.seriesId)===seriesId).sort((a,b)=>Number(a.revision)-Number(b.revision));
  if(indexes.some(row=>dataOpsCloseText(row.companyId)!==companyId||dataOpsCloseText(row.closeBusinessDate)!==closeBusinessDate))throw new Error('CLOSE_CONTEXT_SCOPE_MISMATCH');
  const byRevision=new Map(indexes.map(row=>[Number(row.revision),row])),effectiveRevision=Number(pointer&&pointer.currentEffectiveRevision||0),effective=effectiveRevision?byRevision.get(effectiveRevision)||null:null;
  let prior=null;const allIndexes=dataOpsCloseRows(dataOpsCloseIndexSheet(ss)),allPointers=dataOpsClosePointers(properties);for(const candidateSeries of Object.keys(allPointers)){const candidatePointer=allPointers[candidateSeries]||{},effectiveId=dataOpsCloseText(candidatePointer.currentEffectiveRevisionId);if(!effectiveId)continue;const row=allIndexes.find(item=>dataOpsCloseText(item.closeRevisionId)===effectiveId&&dataOpsCloseText(item.seriesId)===candidateSeries);if(!row||dataOpsCloseText(row.companyId)!==companyId||dataOpsCloseText(row.closeBusinessDate)>=closeBusinessDate)continue;if(!prior||dataOpsCloseText(row.closeBusinessDate)>dataOpsCloseText(prior.closeBusinessDate))prior=row;}
  const priorResult=prior&&prior.stageId?dataOpsCloseReadStageJson(ss,prior.stageId,'B'):null,baselines=dataOpsCloseRows(dataOpsCloseBaselineSheet(ss)).filter(row=>dataOpsCloseText(row.companyId)===companyId&&dataOpsCloseText(row.status)==='APPROVED').map(row=>JSON.parse(row.payload||'{}'));
  const context={series:{closeSeriesId:seriesId,seriesHeadRevision:indexes.length?Number(indexes[indexes.length-1].revision):0,seriesHeadRevisionId:indexes.length?dataOpsCloseText(indexes[indexes.length-1].closeRevisionId):'',currentEffectiveRevision:effectiveRevision,currentEffectiveRevisionId:effective?dataOpsCloseText(effective.closeRevisionId):'',previousEffectiveRevision:Number(pointer&&pointer.previousEffectiveRevision||0),previousEffectiveRevisionId:dataOpsCloseText(pointer&&pointer.previousEffectiveRevisionId)},currentReceipt:effective?JSON.parse(effective.receipt||'{}'):null,priorEffectiveReceipt:prior?JSON.parse(prior.receipt||'{}'):null,priorInventoryRows:priorResult&&Array.isArray(priorResult.inventoryRows)?priorResult.inventoryRows:[],approvedBaselines:baselines,authority:'CLOUD_CLOSE_INDEX'};context.contextDigest=dataOpsSituationDigest(context);dataOpsCloseAudit(ss,{action:'CONTEXT',actorId:auth.actorId,roleIds:auth.roleIds,scopeDigest:auth.scopeDigest,seriesId,detail:{contextDigest:context.contextDigest}});return context;
}
function dataOpsCloseDecisionDigest(rows){const latest={};(rows||[]).forEach(row=>{if(!dataOpsCloseText(row.issueId)||!dataOpsCloseText(row.issueDecisionId)||!dataOpsCloseText(row.decisionDigest))throw new Error('CLOSE_ISSUE_DECISION_INVALID');if(!latest[row.issueId]||String(latest[row.issueId].decidedAt)<String(row.decidedAt))latest[row.issueId]=row;});return dataOpsSituationDigest(Object.keys(latest).sort().map(issueId=>({issueId,latestDecisionId:latest[issueId].issueDecisionId,decisionDigest:latest[issueId].decisionDigest})));}
function dataOpsCloseLogicalResultDigest(result){const logical=JSON.parse(JSON.stringify(result||{}));delete logical.closeRevisionId;delete logical.resultBDigest;delete logical.resultSnapshotId;Object.keys(logical).forEach(key=>{if(!Array.isArray(logical[key]))return;logical[key].forEach(row=>Object.keys(row||{}).forEach(field=>{if(field==='closeRevisionId'||/^close.*(?:RowId|RevisionId)$/i.test(field)||field==='auditEventId')delete row[field];}));});return dataOpsSituationDigest(logical);}
function dataOpsCloseReportDigest(report){return dataOpsSituationDigest({closeRevisionId:report.closeRevisionId,templateVersion:report.templateVersion,resultBDigest:report.resultBDigest,sheets:report.sheets});}
function dataOpsCloseEnsureAudit(ss,auditId,row){const sheet=dataOpsCloseSheet(ss,DATAOPS_CLOSE_SHEETS.AUDIT,['auditId','action','actorId','roleIds','scopeDigest','seriesId','commandId','result','detail','createdAt']);if(dataOpsCloseRows(sheet).some(item=>dataOpsCloseText(item.auditId)===auditId))return;sheet.appendRow([auditId,row.action,row.actorId,(row.roleIds||[]).join(','),row.scopeDigest,row.seriesId||'',row.commandId||'',row.result||'SUCCESS',JSON.stringify(row.detail||{}),new Date().toISOString()]);}
function dataOpsCloseVerifyReadSources(ss,payload,auth,properties){
  const snapshot=payload.closeSnapshotA||{},orderRequest=payload.orderqReadRequest||{},orderSession=orderQM9SituationReadCached('SESSION',orderRequest.readSessionId);
  if(!orderSession||orderSession.status!=='CONSUMED'||dataOpsCloseText(orderRequest.tokenDigest)!==dataOpsCloseText(orderSession.tokenDigest)||Date.now()>=Date.parse(orderSession.expiresAt))throw new Error('CLOSE_READ_TOKEN_INVALID');
  const orderUnsigned={...orderSession,status:'OPEN'};delete orderUnsigned.tokenDigest;delete orderUnsigned.crossAuthorityHandshakeDigest;delete orderUnsigned.consumedAt;
  if(!dataOpsSituationConstantTime(orderSession.tokenDigest,orderQM9Digest(orderUnsigned))||auth.actorId!==orderSession.actorId||auth.scopeDigest!==orderSession.scopeDigest)throw new Error('CLOSE_READ_TOKEN_INVALID');
  const stored=dataOpsSituationReadSessions(ss).rows.find(row=>row.readSessionId===orderSession.dataOpsReadSessionId),dataSession=stored&&stored.payload,dataToken=dataOpsCloseText(payload.dataopsReadTokenDigest);
  if(!dataSession||stored.status!=='CONSUMED'||Date.now()>=Date.parse(dataSession.expiresAt)||auth.actorId!==dataSession.actorId||auth.scopeDigest!==dataSession.scopeDigest)throw new Error('CLOSE_READ_TOKEN_INVALID');
  const dataUnsigned={...dataSession,status:'OPEN'};delete dataUnsigned.tokenDigest;delete dataUnsigned.consumedAt;
  if(!dataOpsSituationConstantTime(dataSession.tokenDigest,dataOpsSituationSessionToken(dataUnsigned,properties))||!dataOpsSituationConstantTime(dataSession.tokenDigest,dataToken))throw new Error('CLOSE_READ_TOKEN_INVALID');
  const dataDeployment=dataOpsSituationRequireDeployment(properties),orderDeployment=orderQM9SituationDeployment(properties);
  if(dataDeployment.deploymentId!==dataSession.deploymentId||dataDeployment.deploymentVersion!==dataSession.deploymentVersion||dataDeployment.gitCommit!==dataSession.gitCommit||orderDeployment.deploymentId!==orderSession.deploymentId||orderDeployment.deploymentVersion!==orderSession.deploymentVersion||orderDeployment.gitCommit!==orderSession.gitCommit)throw new Error('CLOSE_DEPLOYMENT_CHANGED_AFTER_SEAL');
  const orderHead=snapshot.orderq&&snapshot.orderq.head,dataHead=snapshot.dataops&&snapshot.dataops.head,currentOrder=orderQM9SituationHeadState(ss),currentData=dataOpsSituationCurrentSnapshot(ss,properties),currentDataDigest=dataOpsSituationDigest(currentData.snapshot.manifest);
  if(!orderHead||!dataHead||dataOpsCloseText(orderHead.frozenTokenDigest)!==orderSession.tokenDigest||Number(orderHead.currentHeadRevision)!==Number(orderSession.headRevision)||dataOpsCloseText(orderHead.currentHeadDigest)!==orderSession.headDigest||dataOpsCloseText(dataHead.frozenTokenDigest)!==dataSession.tokenDigest||Number(dataHead.currentHeadRevision)!==Number(dataSession.headRevision)||dataOpsCloseText(dataHead.currentHeadDigest)!==dataSession.headDigest||Number(currentOrder.revision)!==Number(orderSession.headRevision)||currentOrder.digest!==orderSession.headDigest||Number(currentData.snapshot.manifest.snapshotRevision)!==Number(dataSession.headRevision)||currentDataDigest!==dataSession.headDigest)throw new Error('CLOSE_SOURCE_CHANGED_BEFORE_SEAL');
  const tokenCore={orderqReadSessionId:orderSession.readSessionId,orderqTokenDigest:orderSession.tokenDigest,dataopsReadSessionId:dataSession.readSessionId,dataopsTokenDigest:dataSession.tokenDigest,crossAuthorityHandshakeDigest:orderSession.crossAuthorityHandshakeDigest,expiresAt:new Date(Math.min(Date.parse(orderSession.expiresAt),Date.parse(dataSession.expiresAt))).toISOString()};return{tokenDigest:dataOpsSituationDigest(tokenCore),orderq:orderSession,dataops:dataSession,expiresAt:tokenCore.expiresAt};
}
function dataOpsCloseSeal(ss,payload,auth){const properties=PropertiesService.getScriptProperties(),verified=dataOpsCloseVerifyReadSources(ss,payload,auth,properties),snapshot=payload.closeSnapshotA||{},sourceADigest=dataOpsSituationDigest(snapshot),closeDeployment=dataOpsCloseDeployment(properties),capabilityDigest=dataOpsSituationDigest({expected:closeDeployment,actions:DATAOPS_CLOSE_ACTIONS});if(sourceADigest!==dataOpsCloseText(payload.sourceADigest)||!dataOpsCloseText(payload.closeSeriesId)||dataOpsCloseText(payload.capabilityDigest)!==capabilityDigest)throw new Error('CLOSE_SOURCE_DIGEST_INVALID');const receipt={sourceSealId:'CSS-'+Utilities.getUuid(),closeSeriesId:dataOpsCloseText(payload.closeSeriesId),sourceADigest,closeReadTokenDigest:verified.tokenDigest,orderqHeadDigestAtSeal:dataOpsCloseText(verified.orderq.headDigest),dataopsHeadDigestAtSeal:dataOpsCloseText(verified.dataops.headDigest),orderqDeployment:{deploymentId:verified.orderq.deploymentId,deploymentVersion:verified.orderq.deploymentVersion,gitCommit:verified.orderq.gitCommit},dataopsDeployment:{deploymentId:verified.dataops.deploymentId,deploymentVersion:verified.dataops.deploymentVersion,gitCommit:verified.dataops.gitCommit},closeDeployment,capabilityDigest,sealedBy:auth.actorId,sealedAt:new Date().toISOString()};if(!receipt.orderqHeadDigestAtSeal||!receipt.dataopsHeadDigestAtSeal||!receipt.capabilityDigest)throw new Error('CLOSE_SOURCE_SEAL_INVALID');receipt.receiptFingerprint=dataOpsSituationDigest(receipt);dataOpsCloseSealSheet(ss).appendRow([receipt.sourceSealId,receipt.closeSeriesId,receipt.sourceADigest,receipt.closeReadTokenDigest,receipt.orderqHeadDigestAtSeal,receipt.dataopsHeadDigestAtSeal,JSON.stringify(receipt.orderqDeployment),JSON.stringify(receipt.dataopsDeployment),receipt.capabilityDigest,receipt.sealedBy,receipt.sealedAt,receipt.receiptFingerprint,JSON.stringify(receipt)]);dataOpsCloseAudit(ss,{action:'SEAL',actorId:auth.actorId,roleIds:auth.roleIds,scopeDigest:auth.scopeDigest,seriesId:receipt.closeSeriesId,detail:{sourceSealId:receipt.sourceSealId}});return receipt;}
function dataOpsClosePrepare(ss,payload,auth){
  const intent=payload.intent||{},seriesId=dataOpsCloseText(intent.closeSeriesId),commandId=dataOpsCloseText(intent.commandId),idempotencyKey=dataOpsCloseText(intent.idempotencyKey),fingerprint=dataOpsCloseText(intent.fingerprint),stageId=dataOpsCloseText(intent.stageId),actionType=dataOpsCloseText(intent.actionType),manifest=Array.isArray(intent.stageManifest)?intent.stageManifest:[];
  if(!seriesId||!commandId||!idempotencyKey||!/^[a-f0-9]{64}$/.test(fingerprint)||!stageId||!['POST_CLOSE','CORRECT_CLOSE','REVERSE_CLOSE'].includes(actionType)||JSON.stringify(manifest.map(row=>row.kind))!==JSON.stringify(['A','B','ISSUES','DECISIONS','REPORT','BASELINES']))throw new Error('DATAOPS_CLOSE_INTENT_INVALID');
  let totalCount=0,totalBytes=0;manifest.forEach(row=>{if(!Number.isInteger(Number(row.chunkCount))||Number(row.chunkCount)<1||!Number.isInteger(Number(row.totalBytes))||Number(row.totalBytes)<1||!/^[a-f0-9]{64}$/.test(dataOpsCloseText(row.payloadDigest))||!Array.isArray(row.chunkDigests)||row.chunkDigests.length!==Number(row.chunkCount)||row.chunkDigests.some(value=>!/^[a-f0-9]{64}$/.test(dataOpsCloseText(value))))throw new Error('DATAOPS_CLOSE_STAGE_MANIFEST_INVALID');totalCount+=Number(row.chunkCount);totalBytes+=Number(row.totalBytes);});if(totalCount>512||totalBytes>20*1024*1024)throw new Error('DATAOPS_CLOSE_PAYLOAD_TOO_LARGE');
  const seal=dataOpsCloseFindSeal(ss,intent.sourceSealId).receipt,sealed=intent.sealedVerification||{};if(seal.closeSeriesId!==seriesId||seal.sourceADigest!==intent.sourceADigest||seal.receiptFingerprint!==intent.sourceSealReceiptFingerprint||seal.orderqHeadDigestAtSeal!==sealed.orderqHeadDigest||seal.dataopsHeadDigestAtSeal!==sealed.dataopsHeadDigest||seal.capabilityDigest!==sealed.capabilityDigest||sealed.resultBDigest!==intent.resultBDigest||sealed.issueDecisionDigest!==intent.issueDecisionDigest)throw new Error('CLOSE_SOURCE_SEAL_MISMATCH');
  const sheet=dataOpsCloseLeaseSheet(ss),prior=dataOpsCloseFindLease(ss,seriesId);if(prior&&prior.status==='PREPARED'&&Date.parse(prior.expiresAt)>Date.now()&&prior.commandId!==commandId)throw new Error('DATAOPS_CLOSE_LEASE_CONFLICT');if(prior&&prior.idempotencyKey===idempotencyKey&&prior.fingerprint!==fingerprint)throw new Error('DATAOPS_CLOSE_IDEMPOTENCY_CONFLICT');
  const expiresAt=new Date(Date.now()+120000).toISOString(),now=new Date().toISOString(),row=[seriesId,commandId,idempotencyKey,fingerprint,'PREPARED',stageId,expiresAt,now,JSON.stringify(sealed),actionType,Number(intent.expectedSeriesHeadRevision||0),Number(intent.targetRevision||0),auth.actorId,auth.scopeDigest,seal.sourceSealId,seal.receiptFingerprint,JSON.stringify(manifest)];if(prior)sheet.getRange(prior._row,1,1,row.length).setValues([row]);else sheet.appendRow(row);dataOpsCloseAudit(ss,{action:'PREPARE',actorId:auth.actorId,roleIds:auth.roleIds,scopeDigest:auth.scopeDigest,seriesId,commandId});return{seriesId,stageId,status:'PREPARED',expiresAt};
}
function dataOpsCloseWriteChunks(ss,payload,auth){
  const stageId=dataOpsCloseText(payload.stageId),kind=dataOpsCloseText(payload.kind),commandId=dataOpsCloseText(payload.commandId),chunks=Array.isArray(payload.chunks)?payload.chunks:[],lease=dataOpsCloseRows(dataOpsCloseLeaseSheet(ss)).find(row=>row.stageId===stageId),manifest=lease&&JSON.parse(lease.stageManifest||'[]'),expected=manifest&&manifest.find(row=>row.kind===kind);
  if(!lease||lease.status!=='PREPARED'||lease.commandId!==commandId||lease.actorId!==auth.actorId||lease.scopeDigest!==auth.scopeDigest||Date.parse(lease.expiresAt)<=Date.now()||!expected||chunks.length!==Number(expected.chunkCount))throw new Error('DATAOPS_CLOSE_LEASE_INVALID');
  const sheet=dataOpsCloseChunkSheet(ss),rows=dataOpsCloseRows(sheet),stageRows=rows.filter(row=>row.stageId===stageId),projected=new Map(stageRows.map(row=>[row.kind+'|'+Number(row.chunkIndex),String(row.content||'')]));
  chunks.forEach((chunk,ordinal)=>{const content=String(chunk.content||''),index=Number(chunk.chunkIndex),digest=dataOpsCloseText(chunk.chunkDigest);if(index!==ordinal||digest!==expected.chunkDigests[ordinal]||content.length>45000||dataOpsSituationUtf8Bytes(content)>45000||dataOpsSituationDigest(content)!==digest)throw new Error('DATAOPS_CLOSE_CHUNK_INVALID');const prior=rows.find(row=>row.stageId===stageId&&row.kind===kind&&Number(row.chunkIndex)===index);if(prior&&prior.chunkDigest!==digest)throw new Error('DATAOPS_CLOSE_CHUNK_CONFLICT');projected.set(kind+'|'+index,content);});
  const combined=chunks.map(row=>String(row.content||'')).join('');if(dataOpsSituationUtf8Bytes(combined)!==Number(expected.totalBytes)||dataOpsSituationDigest(JSON.parse(combined))!==expected.payloadDigest)throw new Error('DATAOPS_CLOSE_STAGE_READBACK_MISMATCH');const totalBytes=[...projected.values()].reduce((sum,content)=>sum+dataOpsSituationUtf8Bytes(content),0);if(projected.size>512||totalBytes>20*1024*1024)throw new Error('DATAOPS_CLOSE_PAYLOAD_TOO_LARGE');
  chunks.forEach(chunk=>{const index=Number(chunk.chunkIndex),prior=rows.find(row=>row.stageId===stageId&&row.kind===kind&&Number(row.chunkIndex)===index);if(!prior)sheet.appendRow([stageId,kind,index,chunk.chunkDigest,String(chunk.content||''),'VERIFIED',new Date().toISOString()]);});dataOpsCloseAudit(ss,{action:'WRITE_CHUNKS',actorId:auth.actorId,roleIds:auth.roleIds,scopeDigest:auth.scopeDigest,seriesId:lease.seriesId,commandId,detail:{stageId,kind,count:chunks.length,totalCount:projected.size,totalBytes}});return{stageId,kind,verifiedCount:chunks.length,totalCount:projected.size,totalBytes};
}
function dataOpsCloseCommit(ss,payload,auth,properties){
  const intent=payload.intent||{},seriesId=dataOpsCloseText(intent.closeSeriesId),commandId=dataOpsCloseText(intent.commandId),lease=dataOpsCloseFindLease(ss,seriesId);if(!lease||!['PREPARED','COMMITTED'].includes(dataOpsCloseText(lease.status))||lease.commandId!==commandId||lease.fingerprint!==dataOpsCloseText(intent.fingerprint)||lease.actionType!==dataOpsCloseText(intent.actionType)||lease.actorId!==auth.actorId||lease.scopeDigest!==auth.scopeDigest)throw new Error('DATAOPS_CLOSE_LEASE_INVALID');if(lease.status==='PREPARED'&&Date.parse(lease.expiresAt)<=Date.now())throw new Error('DATAOPS_CLOSE_LEASE_EXPIRED');
  const seal=dataOpsCloseFindSeal(ss,lease.sourceSealId).receipt,sealed=JSON.parse(lease.sealedVerification||'{}'),currentOrder=orderQM9SituationHeadState(ss),currentData=dataOpsSituationCurrentSnapshot(ss,properties),currentDataDigest=dataOpsSituationDigest(currentData.snapshot.manifest),closeDeployment=dataOpsCloseDeployment(properties),orderDeployment=orderQM9SituationDeployment(properties),dataDeployment=dataOpsSituationRequireDeployment(properties),capabilityDigest=dataOpsSituationDigest({expected:closeDeployment,actions:DATAOPS_CLOSE_ACTIONS});
  if(dataOpsCloseText(currentOrder.digest)!==dataOpsCloseText(seal.orderqHeadDigestAtSeal)||Number(currentOrder.revision)!==Number(sealed.orderqHeadRevision||currentOrder.revision)||currentDataDigest!==dataOpsCloseText(seal.dataopsHeadDigestAtSeal)||JSON.stringify(orderDeployment)!==JSON.stringify(seal.orderqDeployment)||JSON.stringify({deploymentId:dataDeployment.deploymentId,deploymentVersion:dataDeployment.deploymentVersion,gitCommit:dataDeployment.gitCommit})!==JSON.stringify(seal.dataopsDeployment)||JSON.stringify(closeDeployment)!==JSON.stringify(seal.closeDeployment)||capabilityDigest!==seal.capabilityDigest||seal.closeSeriesId!==seriesId||seal.sourceADigest!==intent.sourceADigest||seal.receiptFingerprint!==intent.sourceSealReceiptFingerprint||sealed.capabilityDigest!==seal.capabilityDigest||sealed.resultBDigest!==intent.resultBDigest||sealed.issueDecisionDigest!==intent.issueDecisionDigest)throw new Error('CLOSE_SOURCE_CHANGED_AFTER_SEAL');
  if(Number(intent.expectedSeriesHeadRevision||0)!==Number(lease.expectedSeriesHeadRevision||0)||Number(intent.targetRevision||0)!==Number(lease.targetRevision||0))throw new Error('CLOSE_REVISION_CONFLICT');
  const manifest=JSON.parse(lease.stageManifest||'[]'),expectedKinds=['A','B','ISSUES','DECISIONS','REPORT','BASELINES'];if(JSON.stringify(manifest.map(row=>row.kind))!==JSON.stringify(expectedKinds))throw new Error('CLOSE_STAGE_READBACK_REQUIRED');const values={};for(const kind of expectedKinds){const expected=manifest.find(row=>row.kind===kind),staged=dataOpsCloseStagePayload(ss,lease.stageId,kind);if(staged.rows.length!==Number(expected.chunkCount)||staged.rows.some((row,index)=>row.status!=='VERIFIED'||Number(row.chunkIndex)!==index||row.chunkDigest!==expected.chunkDigests[index])||dataOpsSituationUtf8Bytes(staged.content)!==Number(expected.totalBytes))throw new Error('CLOSE_STAGE_READBACK_REQUIRED');values[kind]=JSON.parse(staged.content);if(dataOpsSituationDigest(values[kind])!==expected.payloadDigest)throw new Error('CLOSE_STAGE_READBACK_MISMATCH');}
  if(dataOpsSituationDigest(values.A)!==intent.sourceADigest||dataOpsCloseLogicalResultDigest(values.B)!==intent.resultBDigest||dataOpsCloseDecisionDigest(values.DECISIONS)!==intent.issueDecisionDigest||dataOpsCloseReportDigest(values.REPORT)!==intent.reportDigest)throw new Error('CLOSE_STAGE_DIGEST_MISMATCH');const unsigned={...intent};delete unsigned.fingerprint;delete unsigned.finalReceiptFingerprint;const expectedFingerprint=dataOpsSituationDigest(unsigned),expectedReceiptFingerprint=dataOpsSituationDigest({...unsigned,fingerprint:expectedFingerprint});if(intent.fingerprint!==expectedFingerprint||intent.finalReceiptFingerprint!==expectedReceiptFingerprint)throw new Error('CLOSE_INTENT_FINGERPRINT_INVALID');
  const indexSheet=dataOpsCloseIndexSheet(ss),indexes=dataOpsCloseRows(indexSheet),same=indexes.find(row=>row.finalReceiptFingerprint===intent.finalReceiptFingerprint),seriesRows=indexes.filter(row=>row.seriesId===seriesId),pointers=dataOpsClosePointers(properties),pointer=pointers[seriesId]||{};if(!same&&(seriesRows.length!==Number(intent.expectedSeriesHeadRevision||0)||Number(pointer.seriesHeadRevision||0)!==Number(intent.expectedSeriesHeadRevision||0)||Number(pointer.currentEffectiveRevision||0)!==Number(intent.expectedEffectiveRevision||0)))throw new Error('CLOSE_REVISION_CONFLICT');if(!same&&intent.actionType==='POST_CLOSE'&&Number(pointer.seriesHeadRevision||0)!==0)throw new Error('CLOSE_REVISION_CONFLICT');if(!same&&intent.actionType==='CORRECT_CLOSE'&&Number(pointer.currentEffectiveRevision||0)<=0)throw new Error('CLOSE_REVISION_CONFLICT');if(!same&&intent.actionType==='REVERSE_CLOSE'&&Number(intent.targetRevision)!==Number(pointer.currentEffectiveRevision||0))throw new Error('CLOSE_REVERSE_TARGET_INVALID');if(same&&(same.commandId&&same.commandId!==commandId))throw new Error('CLOSE_IDEMPOTENCY_CONFLICT');
  let receipt=same?JSON.parse(same.receipt):null;if(!receipt){const priorEffective=Number(pointer.currentEffectiveRevision||0),priorEffectiveId=dataOpsCloseText(pointer.currentEffectiveRevisionId);let nextEffective=Number(intent.revision),nextEffectiveId=intent.closeRevisionId;if(intent.actionType==='REVERSE_CLOSE'){nextEffective=Number(intent.previousEffectiveRevision||0);nextEffectiveId=dataOpsCloseText(intent.previousEffectiveRevisionId);}const committedAt=new Date().toISOString(),nextPointer={seriesHeadRevision:Number(intent.revision),seriesHeadRevisionId:intent.closeRevisionId,currentEffectiveRevision:nextEffective,currentEffectiveRevisionId:nextEffectiveId,previousEffectiveRevision:priorEffective,previousEffectiveRevisionId:priorEffectiveId,updatedAt:committedAt};receipt={closeRevisionId:intent.closeRevisionId,closeSeriesId:seriesId,revision:Number(intent.revision),actionType:intent.actionType,finalReceiptFingerprint:intent.finalReceiptFingerprint,status:'COMMITTED',committedAt,stageId:lease.stageId,sourceSealId:seal.sourceSealId,nextPointer};indexSheet.appendRow([receipt.closeRevisionId,seriesId,receipt.revision,intent.actionType,intent.sourceADigest,intent.resultBDigest,intent.issueDecisionDigest,intent.finalReceiptFingerprint,JSON.stringify(receipt),receipt.committedAt,lease.stageId,dataOpsCloseText(intent.companyId),dataOpsCloseText(intent.closeBusinessDate),intent.reportDigest,commandId]);const readBack=dataOpsCloseRows(indexSheet).find(row=>row.closeRevisionId===receipt.closeRevisionId&&row.finalReceiptFingerprint===receipt.finalReceiptFingerprint);if(!readBack)throw new Error('CLOSE_INDEX_READBACK_REQUIRED');}
  if(values.BASELINES.length){if(!same&&(intent.actionType!=='POST_CLOSE'||Number(intent.expectedSeriesHeadRevision)!==0||pointer.currentEffectiveRevision))throw new Error('CLOSE_OPENING_BASE_CONFLICT');const sheet=dataOpsCloseBaselineSheet(ss),rows=dataOpsCloseRows(sheet);for(const baseline of values.BASELINES){if(!dataOpsCloseText(baseline.baselineId)||baseline.status!=='APPROVED'||dataOpsCloseText(baseline.companyId)!==dataOpsCloseText(intent.companyId)||!dataOpsCloseText(baseline.inventoryKey)||!Number.isFinite(Number(baseline.orderqLedgerUpperBound))||!dataOpsCloseText(baseline.approvedBy)||!dataOpsCloseText(baseline.approvalReason)||!dataOpsCloseText(baseline.sourceReceiptFingerprint))throw new Error('CLOSE_OPENING_BASE_INVALID');const payload=JSON.stringify(baseline),contextDigest=dataOpsSituationDigest({seriesId,companyId:intent.companyId,closeBusinessDate:intent.closeBusinessDate,baseline});const prior=rows.find(row=>row.baselineId===baseline.baselineId);if(prior&&prior.payload!==payload)throw new Error('CLOSE_OPENING_BASE_CONFLICT');if(!prior){if(same)throw new Error('CLOSE_OPENING_BASE_READBACK_REQUIRED');sheet.appendRow([baseline.baselineId,seriesId,intent.companyId,intent.closeBusinessDate,'KRW',contextDigest,payload,baseline.approvedBy,baseline.approvalReason,baseline.approvedAt,'APPROVED']);}}}
  if(!receipt.nextPointer||receipt.nextPointer.seriesHeadRevisionId!==receipt.closeRevisionId)throw new Error('CLOSE_POINTER_INVALID');pointers[seriesId]=receipt.nextPointer;properties.setProperty(DATAOPS_CLOSE_PROPERTIES.POINTERS,JSON.stringify(pointers));const readPointer=dataOpsClosePointers(properties)[seriesId];if(!readPointer||JSON.stringify(readPointer)!==JSON.stringify(receipt.nextPointer))throw new Error('CLOSE_POINTER_READBACK_REQUIRED');dataOpsCloseLeaseSheet(ss).getRange(lease._row,5).setValue('COMMITTED');dataOpsCloseEnsureAudit(ss,'AUDIT-COMMIT-'+commandId,{action:'COMMIT',actorId:auth.actorId,roleIds:auth.roleIds,scopeDigest:auth.scopeDigest,seriesId,commandId,detail:{revision:receipt.revision,recovered:Boolean(same)}});return receipt;
}
function dataOpsCloseHandleAction(ss,action,payload){const properties=PropertiesService.getScriptProperties(),deployment=dataOpsCloseDeployment(properties);if(action==='dataops_close_ping')return{contractVersion:DATAOPS_CLOSE_V1,capabilityVersion:DATAOPS_CLOSE_V1,...deployment,actions:DATAOPS_CLOSE_ACTIONS};const actionType=dataOpsCloseText(payload&&payload.intent&&payload.intent.actionType),role=action==='dataops_close_commit'?(actionType==='CORRECT_CLOSE'?'DATAOPS_CLOSE_CORRECT':actionType==='REVERSE_CLOSE'?'DATAOPS_CLOSE_REVERSE':'DATAOPS_CLOSE_COMMIT'):action==='dataops_close_prepare'||action==='dataops_close_write_chunks'||action==='dataops_close_abort'?'DATAOPS_CLOSE_RECONCILE':'DATAOPS_CLOSE_READ',auth=dataOpsSituationRequireAuth(payload,role,properties);try{if(action==='dataops_close_context')return dataOpsCloseContext(ss,payload,auth,properties);if(action==='dataops_close_prepare')return dataOpsClosePrepare(ss,payload,auth);if(action==='dataops_close_seal')return dataOpsCloseSeal(ss,payload,auth);if(action==='dataops_close_write_chunks')return dataOpsCloseWriteChunks(ss,payload,auth);if(action==='dataops_close_commit')return dataOpsCloseCommit(ss,payload,auth,properties);if(action==='dataops_close_abort'){const lease=dataOpsCloseFindLease(ss,dataOpsCloseText(payload.closeSeriesId));if(lease&&(lease.actorId!==auth.actorId||lease.scopeDigest!==auth.scopeDigest||lease.commandId!==dataOpsCloseText(payload.commandId)))throw new Error('DATAOPS_CLOSE_LEASE_INVALID');if(lease)dataOpsCloseLeaseSheet(ss).getRange(lease._row,5).setValue('ABORTED');return{status:'ABORTED'};}throw new Error('DATAOPS_CLOSE_ACTION_UNSUPPORTED');}catch(error){dataOpsCloseAudit(ss,{action,actorId:auth.actorId,roleIds:auth.roleIds,scopeDigest:auth.scopeDigest,result:'FAILURE',detail:{code:dataOpsCloseText(error&&error.message)}});throw error;}}
