import { listOfficialSales, listLegacySales, loadOfficialSaleAggregate, loadLegacySaleAggregate, runCentralOfficialVoucherCommand } from './official-voucher-repository.js?v=0.20.0';
import { buildOfficialSaleEditCommand, mergeOfficialSaleConflictEdits, officialSaleEvidence } from './sale-official-editor.js?v=0.20.0';
import { loadSaleStage4Capability } from '../smartinput/sale-official-stage4.js?v=0.2.0';
import { pullCentralOfficialState } from './central-command-gateway.js?v=0.19.0';

const $=id=>document.getElementById(id), text=value=>String(value??''), esc=value=>text(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
let documents=[], current=null, selectedId='', capability={ready:false}, busy=false;
function status(row){return text(row.businessStatus||row.status||'DRAFT').toUpperCase();}
function message(value,type=''){$('message').textContent=value;$('message').className=`purchase-message ${type}`;}
function setBusy(value){busy=value;document.querySelectorAll('button').forEach(button=>button.disabled=value);}
function renderList(){ $('saleList').innerHTML=documents.length?documents.map(row=>`<button class="purchase-card ${row.salesDocumentId===selectedId?'selected':''}" data-id="${esc(row.salesDocumentId)}"><strong>${esc(row.salesDocumentId)} <span class="purchase-status">${row.contractKind==='SALE_STAGE4_V1'?'공식':'기존'} · ${esc(status(row))}</span></strong><span>${esc(row.salesCustomerName||row.salesCustomerId||'거래처 미지정')} · ${esc(row.saleDate||'-')}</span><span>${Number(row.totalAmount||0).toLocaleString('ko-KR')}원</span></button>`).join(''):'<div class="empty-state">판매전표가 없습니다.</div>'; $('summaryText').textContent=`판매 ${documents.length}건`; }
function lineFields(line,index,editable){return `<section class="purchase-line" data-line="${index}"><div class="purchase-form-grid"><label>상품 ID<input class="product" value="${esc(line.productId)}" readonly></label><label>창고 ID<input class="warehouse" value="${esc(line.warehouseId)}" readonly></label><label>실제수량<input class="actual" type="number" step="any" value="${esc(line.actualQuantity)}" ${editable?'':'readonly'}></label><label>실제단위<input class="unit" value="${esc(line.actualUnit||line.unit)}" readonly></label><label>기준환산<input class="baseFactor" type="number" step="any" value="${esc(line.actualToBaseFactor)}" readonly></label><label>주문환산<input class="recognizedFactor" type="number" step="any" value="${esc(line.actualToRecognizedFactor)}" readonly></label><label>단가<input class="price" type="number" step="any" value="${esc(line.unitPrice)}" ${editable?'':'readonly'}></label><label>공급가액<input value="${esc(line.supplyAmount)}" readonly></label></div></section>`;}
function renderDetail(){if(!current){$('saleDetail').innerHTML='<div class="empty-state">판매전표를 선택하세요.</div>';return;}const official=current.document.contractKind==='SALE_STAGE4_V1';const editable=official&&status(current.document)==='CONFIRMED';$('saleDetail').innerHTML=`<form id="saleForm" class="purchase-form"><h2>${official?'공식':'기존'} 판매전표 · ${esc(status(current.document))}</h2><div class="purchase-form-grid"><label>판매 ID<input value="${esc(current.document.salesDocumentId)}" readonly></label><label>Revision<input value="${esc(current.document.revision)}" readonly></label><label>판매처<input id="salesCustomer" value="${esc(current.document.salesCustomerId)}" readonly></label><label>배송처<input id="deliveryCustomer" value="${esc(current.document.deliveryCustomerId)}" readonly></label><label>청구처<input id="billingCustomer" value="${esc(current.document.billingCustomerId)}" readonly></label><label>판매일자<input id="saleDate" type="date" value="${esc(current.document.saleDate)}" ${editable?'':'readonly'}></label></div><div>${(current.activeLines||current.lines||[]).map((line,index)=>lineFields(line,index,editable)).join('')}</div>${editable?'<label>수정·취소 사유<input id="reason"></label><div class="purchase-actions"><button class="pq-btn primary" data-action="correct" type="button">수정 저장</button><button class="pq-btn danger" data-action="reverse" type="button">전체 취소</button></div>':''}<pre class="purchase-evidence">${esc(JSON.stringify(official?officialSaleEvidence(current):{schemaVersion:'ORDERQ_SALE_EVIDENCE_LEGACY_FALLBACK_V1',legacyFallback:true,lines:current.lines,movements:current.movements},null,2))}</pre></form>`;if(official&&!capability.ready)message('실제 Stage4 Cloud 배포 식별자가 확인되지 않아 수정·취소가 비활성화됩니다.','error');}
function command(action){const form=$('saleForm'), base=current.activeLines||[];const lines=[...form.querySelectorAll('[data-line]')].map((node,index)=>({...base[index],productId:text(node.querySelector('.product').value),warehouseId:text(node.querySelector('.warehouse').value),actualQuantity:node.querySelector('.actual').value,actualUnit:text(node.querySelector('.unit').value),actualToBaseFactor:node.querySelector('.baseFactor').value,actualToRecognizedFactor:node.querySelector('.recognizedFactor').value,unitPrice:node.querySelector('.price').value}));return buildOfficialSaleEditCommand({action,document:{...current.document,salesCustomerId:text($('salesCustomer').value),deliveryCustomerId:text($('deliveryCustomer').value),billingCustomerId:text($('billingCustomer').value),saleDate:text($('saleDate').value)},lines,reason:text($('reason').value),occurredAt:new Date().toISOString()});}
async function submitAction(action){const edited=command(action);await pullCentralOfficialState();const fresh=await loadOfficialSaleAggregate(selectedId);if(!fresh||Number(fresh.document.revision)!==Number(current.document.revision)){current=mergeOfficialSaleConflictEdits({document:edited.document,lines:edited.lines},fresh||{});renderDetail();throw new Error('ORDERQ_SALE_REVISION_CONFLICT');}const edits=new Map(edited.lines.map(line=>[text(line.lineIdentityId||line.sourceLineKey),line]));const lines=(fresh.activeLines||[]).map(line=>{const edit=edits.get(text(line.lineIdentityId||line.sourceLineKey))||{};return {...line,actualQuantity:edit.actualQuantity,unitPrice:edit.unitPrice};});const source=buildOfficialSaleEditCommand({action,document:{...fresh.document,saleDate:edited.document.saleDate},lines,reason:edited.reason,occurredAt:new Date().toISOString()});return runCentralOfficialVoucherCommand(source);}
async function reload(){const filters={status:$('statusFilter').value,search:$('searchFilter').value};const [official,legacy]=await Promise.all([listOfficialSales(filters),listLegacySales(filters)]);documents=[...official,...legacy];renderList();if(selectedId){const selected=documents.find(row=>row.salesDocumentId===selectedId);current=selected?.contractKind==='SALE_STAGE4_V1'?await loadOfficialSaleAggregate(selectedId):await loadLegacySaleAggregate(selectedId);}renderDetail();}
$('saleList').addEventListener('click',event=>{const button=event.target.closest('[data-id]');if(!button)return;selectedId=button.dataset.id;reload().catch(error=>message(error.message,'error'));});
$('saleDetail').addEventListener('click',event=>{const button=event.target.closest('[data-action]');if(!button||busy)return;if(!capability.ready)return message('ORDERQ_SALE_STAGE4_CAPABILITY_UNAVAILABLE','error');setBusy(true);submitAction(button.dataset.action).then(()=>reload()).catch(error=>message(error.message,'error')).finally(()=>setBusy(false));});
$('refreshBtn').addEventListener('click',()=>reload());$('statusFilter').addEventListener('change',()=>reload());$('searchFilter').addEventListener('input',()=>reload());
capability=await loadSaleStage4Capability();await reload();
