(() => {
  const V='1.0.0',K={theme:'oneapp.nexus.theme',order:'oneapp.nexus.appOrder',hidden:'oneapp.nexus.hiddenApps'};
  const read=(k,d)=>{try{const v=localStorage.getItem(k);return v==null?d:JSON.parse(v)}catch{return d}},write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
  const base=new URL('.',document.currentScript?.src||'/nexus/common/nexus-top.js');
  class NexusTop extends HTMLElement{
    connectedCallback(){if(this.shadowRoot)return;this.apps=Array.isArray(window.NEXUS_APPS)?window.NEXUS_APPS:[];if(!this.apps.length)return;document.documentElement.style.setProperty('--nexus-top-height','44px');this.r=this.attachShadow({mode:'open'});this.r.innerHTML=`<link rel="stylesheet" href="${new URL('nexus-top.css?v='+V,base)}"><div class="top"><a class="brand" href="https://oneapp.orderz.co.kr/nexus/" aria-label="NEXUS HOME"><img src="/nexus/assets/brand/oneapp-nexus-dark.svg" alt="ONEAPP NEXUS"></a><nav class="nav" aria-label="기본 앱"><div class="track"></div></nav><div class="actions"><button class="action" data-open="apps" aria-label="전체 앱" aria-haspopup="dialog" aria-expanded="false"><svg aria-hidden="true" viewBox="0 0 24 24"><path d="M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z"/></svg><span>전체 앱</span></button><button class="action" data-open="settings" aria-label="설정" aria-haspopup="dialog" aria-expanded="false"><svg aria-hidden="true" viewBox="0 0 24 24"><path d="M19 13v-2l2-2-2-3-3 1-2-1-1-3h-3L9 6 7 7 4 6 2 9l2 2v2l-2 2 2 3 3-1 2 1 1 3h3l1-3 2-1 3 1 2-3-2-2zm-7 2a3 3 0 110-6 3 3 0 010 6z"/></svg><span>설정</span></button></div></div><div class="panel apps" data-panel="apps" role="dialog" aria-label="전체 앱" hidden><div class="heading"><div><span class="eyebrow">ONEAPP</span><h2>전체 앱</h2></div><button class="close" aria-label="전체 앱 닫기">×</button></div><div class="grid"></div></div><aside class="panel settings" data-panel="settings" role="dialog" aria-label="NEXUS 설정" hidden><div class="heading"><div><span class="eyebrow">NEXUS</span><h2>설정</h2></div><button class="close" aria-label="설정 닫기">×</button></div><div class="section"><h3>화면 모드</h3><div class="theme"><button data-theme="system">시스템</button><button data-theme="light">일반</button><button data-theme="dark">다크</button></div></div><div class="section"><h3>기본 앱 순서·노출</h3><div class="app-settings"></div><p class="note">숨긴 앱도 전체 앱에서 열고 다시 표시할 수 있습니다.</p></div></aside><div class="backdrop" hidden></div>`;this.open='';this.render();this.bind();this.applyTheme()}
    state(){const ids=this.apps.map(a=>a.id),saved=read(K.order,[]),order=[...saved.filter(x=>ids.includes(x)),...ids.filter(x=>!saved.includes(x))];return{order,hidden:read(K.hidden,[]).filter(x=>ids.includes(x))}}
    render(){const s=this.state(),active=this.getAttribute('app-id')||'',map=Object.fromEntries(this.apps.map(a=>[a.id,a])),apps=s.order.map(id=>map[id]);this.r.querySelector('.track').innerHTML=apps.filter(a=>!s.hidden.includes(a.id)).map(a=>`<a class="tab" href="${a.url}" ${a.id===active?'aria-current="page"':''}>${a.name}</a>`).join('');this.r.querySelector('.grid').innerHTML=apps.map(a=>`<a class="card ${a.id===active?'active':''}" href="${a.url}"><strong>${a.name}</strong><small>${a.brand} · ${a.name}</small></a>`).join('');this.r.querySelector('.app-settings').innerHTML=apps.map((a,i)=>`<div class="app-setting"><button data-move="-1" data-id="${a.id}" aria-label="${a.name} 위로" ${i?'':'disabled'}>↑</button><strong>${a.name}</strong><input type="checkbox" data-visible="${a.id}" aria-label="${a.name} 표시" ${s.hidden.includes(a.id)?'':'checked'}><button data-move="1" data-id="${a.id}" aria-label="${a.name} 아래로" ${i===apps.length-1?'disabled':''}>↓</button></div>`).join('');requestAnimationFrame(()=>this.r.querySelector('[aria-current=page]')?.scrollIntoView({block:'nearest',inline:'center'}))}
    bind(){this.r.addEventListener('click',e=>{const o=e.target.closest('[data-open]');if(o){this.toggle(o.dataset.open,o);return}if(e.target.closest('.close')||e.target.classList.contains('backdrop')){this.close();return}const t=e.target.closest('[data-theme]');if(t){write(K.theme,t.dataset.theme);this.applyTheme();return}const m=e.target.closest('[data-move]');if(m){const s=this.state(),i=s.order.indexOf(m.dataset.id),j=i+Number(m.dataset.move);if(j>=0&&j<s.order.length){[s.order[i],s.order[j]]=[s.order[j],s.order[i]];write(K.order,s.order);this.render()}return}const v=e.target.closest('[data-visible]');if(v){const s=this.state(),id=v.dataset.visible;write(K.hidden,v.checked?s.hidden.filter(x=>x!==id):[...new Set([...s.hidden,id])]);this.render()}});this.r.addEventListener('keydown',e=>{if(e.key==='Escape')this.close()});window.addEventListener('storage',e=>{if(Object.values(K).includes(e.key)){this.render();this.applyTheme()}})}
    toggle(n,b){if(this.open===n){this.close();return}this.close();this.open=n;this.r.querySelector(`[data-panel=${n}]`).hidden=false;this.r.querySelector('.backdrop').hidden=false;b.setAttribute('aria-expanded','true')}
    close(){if(!this.open)return;this.r.querySelector(`[data-panel=${this.open}]`).hidden=true;this.r.querySelector(`[data-open=${this.open}]`).setAttribute('aria-expanded','false');this.r.querySelector('.backdrop').hidden=true;this.open=''}
    applyTheme(){const t=read(K.theme,'system');document.documentElement.dataset.nexusTheme=t;document.documentElement.style.colorScheme=t==='system'?'light dark':t;window.dispatchEvent(new CustomEvent('nexus-theme-change',{detail:{theme:t}}));this.r.querySelectorAll('[data-theme]').forEach(b=>b.classList.toggle('active',b.dataset.theme===t))}
  }customElements.get('nexus-top')||customElements.define('nexus-top',NexusTop)
})();
